# Change these first
owner: shirfan # Your GitHub organization or username, where this repository lives
repo: uptime2 # The name of this repository

sites:
  - name: KOS
    url: $KOS_SITE
    
  - name: Posta
    url: https://posta.ilger.com
    
  - name: KOS 02
    url: https://kos02.ilger.com
    
  - name: smtp2.ilger.com
    check: "tcp-ping"
    url: smtp2.ilger.it
    port: 25
    
  - name: vps.qweb.eu
    check: "tcp-ping"
    url: vps.qweb.eu
    port: 587
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /uptime2
  logoUrl: https://www.ilger.com/wp-content/uploads/2021/11/ILGER-logo.png
  name: Ilger
  introTitle: Ilger
  introMessage: This is a sample status page uses **real-time** data 
  navbar:
    - title: Status
      href: /uptime2
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
